# Generated by Django 2.1.5 on 2019-02-19 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=1000)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_verified', models.BooleanField(default=False)),
                ('director_verified', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('booking_mail_sent', models.BooleanField(default=False)),
                ('street', models.TextField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('reference_name', models.CharField(max_length=30)),
                ('reference_email', models.CharField(max_length=30)),
                ('is_member', models.BooleanField(default=False)),
                ('applied_for_member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
