# Generated by Django 2.1.5 on 2019-02-19 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('arrive', models.DateField()),
                ('depart', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('street', models.TextField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('arrive', models.DateField()),
                ('depart', models.DateField()),
                ('reference_name', models.CharField(max_length=30)),
                ('reference_email', models.CharField(max_length=30)),
                ('reference_designation', models.CharField(max_length=30)),
                ('room_type', models.CharField(max_length=5)),
                ('no_of_rooms', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('childs', models.IntegerField()),
                ('reference_verified', models.BooleanField(default=False)),
                ('director_verified', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('booking_mail_sent', models.BooleanField(default=False)),
                ('admin_verified', models.BooleanField(default=False)),
                ('userbookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='bookingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.FormSubmit'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Room'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
